name: "Greet World"

on: push
#   schedule:
#     - cron: "59 23 * * *"

jobs:
  greet:
    name: greet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: ls -R
    - run: source greet_slowly.sh 
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
