name: "Greet World"

on:
  schedule:
    - cron: '35 20 * * *'

jobs:
  greet:
    name: greet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: source greet_slowly.sh 
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
